export enum EventBusName {
  FLASH_SALE = 'FLASH_SALE',
  PAYMENT_COMPLETED = 'PAYMENT_COMPLETED',
  CREATE_ORDER_PAYMENT = 'CREATE_ORDER_PAYMENT',
  FLASH_SALE_PRODUCT = 'FLASH_SALE_PRODUCT',
  FLASHSALE_SCHEDULE = 'FLASHSALE_SCHEDULE',
}