version: '3.8'
services:
  postgres:
    image: postgres:13
    restart: on-failure
    ports:
      - 5433:5432
    env_file:
      - .env
    volumes:
      - storage-db:/var/lib/postgresql/data

  minio:
    image: quay.io/minio/minio
    restart: on-failure
    ports:
      - 9000:9000
      - 9090:9090
    command: server /data --console-address ":9090"
    volumes:
      - minio-data:/data
    env_file:
      - .env
    environment:
      - MINIO_ROOT_USER=ADMIN
      - MINIO_ROOT_PASSWORD=ADMIN@123
  storage:
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    image: storage_service:latest
    restart: on-failure
    ports:
      - 4006:4006
    env_file:
      - .env

volumes:
  storage-db:
  minio-data:
