version: '3.3'
services:
  mail:
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - 5101:5101
    env_file:
      - .env
    environment:
      - MQ_HOST=host.docker.internal
